In [2]:
import pandas as pd
df = pd.read_csv('/content/salaries_by_college_major.csv')

In [3]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

## Preliminary Data Exploration and Data Cleaning with Pandas

Now that we've got our data loaded into our dataframe,
we need to take a closer look at it to help us understand what it is we are working with. 
This is always the first step with any data science project. Let's see if we can answer the some question

In [4]:
# How many rows does our dataframe have? 
df.shape # This gives us the number of rows and columns (rows, columns)

(51, 6)

In [5]:
# What are the labels for the columns? Do the columns have names?
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [6]:
# Are there any missing values in our dataframe? Does our dataframe contain any bad data?
# we're going to look for NaN (Not A Number) values in our dataframe. NAN values are blank cells 
# or cells that contain strings instead of numbers.
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [7]:
# Also looking at the last few rows of the dataframe
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [8]:
# Deleting the Last Row because it was junk data
clean_df = df.dropna()  
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [9]:
# Accessing a single column like 'starting median salary'
clean_df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [10]:
# Accessing multiple columns
clean_df[['Starting Median Salary', 'Mid-Career Median Salary']]

    Starting Median Salary  Mid-Career Median Salary
0                  46000.0                   77100.0
1                  57700.0                  101000.0
2                  42600.0                   71900.0
3                  36800.0                   61500.0
4                  41600.0                   76800.0
5                  35800.0                   64900.0
6                  38800.0                   64800.0
7                  43000.0                   72100.0
8                  63200.0                  107000.0
9                  42600.0                   79900.0
10                 53900.0                   90500.0
11                 38100.0                   70000.0
12                 61400.0                  105000.0
13                 55900.0                   95500.0
14                 53700.0                   88900.0
15                 35000.0                   56300.0
16                 35900.0                   56900.0
17                 50100.0                   98600.0
18                 34900.0                   52000.0
19                 60900.0                  103000.0
20                 38000.0                   64700.0
21                 37900.0                   68500.0
22                 47900.0                   88300.0
23                 39100.0                   62600.0
24                 41200.0                   65500.0
25                 43500.0                   79500.0
26                 35700.0                   59800.0
27                 38800.0                   60600.0
28                 39200.0                   71000.0
29                 37800.0                   57500.0
30                 57700.0                   94700.0
31                 49100.0                   74800.0
32                 36100.0                   53200.0
33                 40900.0                   80900.0
34                 35600.0                   66700.0
35                 49200.0                   82300.0
36                 40800.0                   79600.0
37                 45400.0                   92400.0
38                 57900.0                   93600.0
39                 35900.0                   55000.0
40                 54200.0                   67000.0
41                 39900.0                   55300.0
42                 39900.0                   81200.0
43                 74300.0                   91700.0
44                 50300.0                   97300.0
45                 40800.0                   78200.0
46                 35900.0                   60400.0
47                 34100.0                   52000.0
48                 36500.0                   58200.0
49                 34000.0                   53100.0

In [11]:
# To find the highest starting salary we can simply chain the .max() method.
clean_df['Starting Median Salary'].max()

74300.0

In [12]:
# Get the row number or index so that we can look up the name of the major. 
clean_df['Starting Median Salary'].idxmax()

np.int64(43)

In [13]:
# Get the name of the major.
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [14]:
# If you don't want a particular column, you can get the whole row.
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

## Sorting Values & Adding Columns

In [20]:
# Trying to see the lowest risk majors
# A low-risk major is a degree where there is a small difference between the lowest and highest salaries. 
# In other words, if the difference between the 10th percentile and the 90th percentile earnings of your major is small, 
# then you can be more certain about your salary after you graduate.
spred_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

# adding a new column to the dataframe at particular index, you could also do clean_df['Spread'] = spred_col
clean_df.insert(5, 'Spread', spred_col) 
clean_df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Spread,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,109800.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,96700.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,113700.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,104200.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,85400.0,Business

In [30]:
# To see which degrees have the smallest spread, we can use the .sort_values() method.
low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [31]:
# Majors with the Highest Potential
high_earn = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
high_earn[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [32]:
# Majors with the Greatest Spread in Salaries
high_spread = clean_df.sort_values('Spread', ascending=False)
high_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

Fun notice from above:
Notice how 3 of the top 5 are present in both. This means that there are some very high earning Economics degree holders, 
but also some who are not earning as much.

## Grouping and Pivoting Data with Pandas

Often times you will want to sum rows that belong to a particular category.
For example, which category of degrees has the highest average salary? Is it STEM, Business or HASS (Humanities, Arts, and Social Science)? 

To answer this question we can to use the .groupby() method.

In [35]:
# For example, We have three categories in the 'Group' column: STEM, HASS and Business. 
# Let's count how many majors we have in each category:
clean_df.groupby('Group').count()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Spread
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [42]:
# Formattinng better
pd.options.display.float_format = '{:,.2f}'.format 

# Now using the .mean() method to find the average salary by group? 
clean_df.groupby('Group').mean(numeric_only=True)

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Spread
Group,,,,,
Business,"44,633.33","75,083.33","43,566.67","147,525.00","103,958.33"
HASS,"37,186.36","62,968.18","34,145.45","129,363.64","95,218.18"
STEM,"53,862.50","90,812.50","56,025.00","157,625.00","101,600.00"